theme: jekyll-theme-minimal
title: Syaerulid Homepage Project
My Project : 
1. iPhone Price Predictor using Machine Learning Model Regression
2. BMI Calculator and Recommendation build with Streamlit

description: Bookmark this to keep an eye on my project updates!
